### PR TITLE
Implement LinearSet

### PR DESCRIPTION
**Pull request by arthurprs**
solves #25 

Implementation straight from HashSet including tests. Only addition is `Into<Vec<K>>`.

### CODE REVIEW

**Comment by FlashCat** [comment]
Thanks for the pull request, and welcome! The contain-rs team is excited to review your changes, and you should hear from @bluss (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way Github handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

**Comment by arthurprs** [comment]
Updated serde support

**Comment by FlashCat** [comment]
:umbrella: The latest upstream changes (presumably #29) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by tormol** [comment]
I have rebased this on master [here](https://github.com/tormol/linear-map/commits/set).  
I don't know serde, but the serde_impl tests passes.

Crate documentation needs to be updated.

**Comment by arthurprs** [comment]
I rebased it on master.

**Comment by Gankro** [comment]
Wow this is some serious dedication to this PR...

**Comment by Gankro** [comment]
MERCY MERGE

**Comment by arthurprs** [comment]
I didn't expect that. Thanks :)

**Pull request merged**
