### PR TITLE
Remove "unzip the vectors?" TODO

### PR DESCRIPTION
**Pull request by tormol**
It belongs on the issue tracker.

Pros:
- No need for custom keys and values iterators.
- Drop the values and convert into a set without allocating.
- Less padding if K and V have different alignment.

Cons:
- Lots of `unsafe` blocks to match performance.
- Memory fragmentation and cache misses:  
  I think `get()`, `insert()` and `iter()` are used more than `contains()`, `keys()` and `values()`.
- extra work in `clear()`, `reserve()` and similar, especially if we use raw pointers.
- Increased struct size.

### CODE REVIEW

**Comment by FlashCat** [comment]
r? @reem

(I've picked a reviewer for you, use r? to override)

**Comment by arthurprs** [comment]
+1, as Linear* are only supposed to be used with very small collections any cache benefits/drawbacks would be really small and not worth the complexity.

What would be interesting instead is an adaptive/allocation-less variant/feature.

**Comment by tormol** [comment]
I don't know what adaptive means, but I [have made](https://github.com/contain-rs/linear-map/pull/31) a borrowed variant.

**Comment by Gankro** [comment]
Thanks!

**Pull request merged**
