### PR TITLE
Assorted cleanup

### PR DESCRIPTION
**Pull request by apasel422**

### CODE REVIEW

**Comment by FlashCat** [comment]
r? @reem

(I've picked a reviewer for you, use r? to override)

**Comment by bluss** [comment]
Heroic cleanup. It looks good to me. I like when the doc points out the element type of the iterator, although I guess it's not that commonplace to do it.

**Comment by apasel422** [comment]
@bluss Should I add back the element type stuff?

**Comment by bluss** [comment]
I think so, it's only better with it. But it should say `&K` not `&'a K` because there is no parameter 'a in scope.

**Comment by bluss** [comment]
I haven't been so involved in contain-rs really, so I'm happy to look over PRs but I don't feel the biggest ownership or knowledge about these projects.

**Comment by apasel422** [comment]
@bluss Updated.

**Comment by bluss** [comment]
Looks good! r+

if all tests and benches have moved out one can set test = false, bench = false for the lib in Cargo.toml. On larger crates it saves compilation time.

**Comment by bluss** [comment]
This crate should have a release, is there anything else we need to do for bumping it to version 0.1.0 or so? I haven't done any releases for contain-rs, but it's about time I figure out how to do it (if it's needed).

**Comment by apasel422** [comment]
We can bump to 1.0.0, but I'd like to take care of #22 first. (And since you mentioned it, the `Cargo.toml` test/bench stuff.)

As far as the release process goes, we haven't been tagging releases or doing much other than publishing to crates.io.

**Comment by bluss** [comment]
#22 doesn't seem like an issue that can be solved anytime soon? We could of course remove the counting entirely.

**Comment by apasel422** [comment]
It seems like #22 can be addressed by using the `vec!` macro and "unique"-ing the vector in-place.

**Pull request merged**
